config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/auto_complete/projects', :to => 'auto_completes#projects', :as => 'auto_complete_projects'

app/views/auto_completes/projects.html.erb
<%= render_project_hierarchy(@projects)%>

app/views/projects/index.html.erb
<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, {:action => 'index', :format => 'atom', :key => User.current.rss_key}) %>
    <%= stylesheet_link_tag "project_filtering", :plugin => "project_filtering" %>
<% end %>

<div class="contextual">
    <%= link_to(l(:label_project_new), {:controller => 'projects', :action => 'new'}, :class => 'icon icon-add') + ' |' if User.current.allowed_to?(:add_project, nil, :global => true) %>
    <%= link_to(l(:label_issue_view_all), issues_path) + ' |' if User.current.allowed_to?(:view_issues, nil, :global => true) %>
    <%= link_to(l(:label_overall_spent_time), time_entries_path) + ' |' if User.current.allowed_to?(:view_time_entries, nil, :global => true) %>
    <%= link_to l(:label_overall_activity),
                { :controller => 'activities', :action => 'index',
                  :id => nil } %>
</div>

<h2><%=l(:label_project_plural)%></h2>
<p><%= label_tag 'project_filter', l(:label_project_filter) %><%= text_field_tag 'project_filter', nil, :autofocus => true %>
<%= javascript_tag "observeSearchfield('project_filter', 'projects-index', '#{ escape_javascript auto_complete_projects_path }')" %>
</p>
<div id="projects-index">
<%= render_project_hierarchy(@projects)%>
</div>

<% if User.current.logged? %>
<p style="text-align:right;">
<span class="my-project"><%= l(:label_my_projects) %></span>
</p>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
<% end %>

<% content_for :sidebar do %>
  <%= form_tag({}, :method => :get) do %>
    <h3><%= l(:label_project_plural) %></h3>
    <label for="closed"><%= check_box_tag 'closed', 1, params[:closed] %> <%= l(:label_show_closed_projects) %></label>
    <p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
  <% end %>
<% end %>

<% html_title(l(:label_project_plural)) -%>